version: '2'
services:
  redis:
    image: "redis:alpine"
    ports: 
      - "6379:6379"
  db:
    image: "registry.cn-shenzhen.aliyuncs.com/weimch/group-project-mysql:v0.0.1"
    ports: 
      - "13306:3306"
  rabbitmq:
    image: "registry.cn-shenzhen.aliyuncs.com/zhangshubo/zhangshubo:v0.0.1"
    ports: 
      - "5672"
  webserver:
    build:
      context: ./src/
      dockerfile: Dockerfile
    ports: 
      - "20080:8080"
    links: 
      - redis
      - db
      - rabbitmq
  mq:
    build:
      context: ../message-queue/
      dockerfile: Dockerfile
    links:
      - rabbitmq
      - db