version: '2'
services:
  redis:
    image: "redis:alpine"
    ports: 
      - "6379"
  projectdb:
    image: "registry.cn-shenzhen.aliyuncs.com/weimch/group-project-mysql:v0.0.1"
    ports: 
      - "13306:3306"
  rabbitmq:
    image: "registry.cn-shenzhen.aliyuncs.com/zhangshubo/zhangshubo:v0.0.1"
    ports: 
      - "5672"
  webserver:
    image: "registry.cn-shenzhen.aliyuncs.com/weimch/group-project-webserver:latest"
    ports: 
      - "20080:8080"
    links: 
      - redis
      - projectdb
      - rabbitmq